[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3

cbor_metadata = false
bytecode_hash = "none"

# to run the test that checks the ticks invariant for all possible tick values, uncomment these two lines
# gas_limit = "18446744073709551615"
# memory_limit = 10000000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.28'
optimizer = true
optimizer_runs = 9999999
via_ir = true
ignored_error_codes = [2394, 6321, 3860, 5574]

[invariant]
fail_on_revert = true
runs = 1

[profile.ci]
verbosity = 3

[profile.ci.fuzz]
runs = 100000
max_test_rejects = 500000

[profile.ci.invariant]
runs = 128

[profile.superfuzz]
verbosity = 3

[profile.superfuzz.fuzz]
runs = 1000000
max_test_rejects = 1000000

[profile.superfuzz.invariant]
runs = 1024
