[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.28'
optimizer = true
optimizer_runs = 4294967295
via_ir = true
ignored_error_codes = [2394, 6321, 3860, 5574]

[invariant]
fail_on_revert = true
runs = 1

[profile.ci]
verbosity = 3

[profile.ci.fuzz]
runs = 100000

[profile.ci.invariant]
runs = 128