name: Deploy Core

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        alchemy_chain_identifiers:
          - eth-sepolia
          - eth-holesky
          # - eth-mainnet
          - worldchain-sepolia
          # - worldchain-mainnet
          - base-sepolia
          # - base-mainnet
          - linea-sepolia
          # - linea-mainnet
          - scroll-sepolia
          # - scroll-mainnet
          - shape-sepolia
          # - shape-mainnet
          - zksync-sepolia
          # - zksync-mainnet
          - opt-sepolia
          # - opt-mainnet
          - polygon-amoy
          # - polygon-mainnet
          - arb-sepolia
          # - arb-mainnet
          - arbnova-sepolia
          # - arbnova-mainnet
          - unichain-sepolia
          # - unichain-mainnet
          - abstract-testnet
          # - abstract-mainnet
          - boba-sepolia
          # - boba-mainnet
          - ink-sepolia
          # - ink-mainnet
          - polygonzkevm-cardona
          # - polygonzkevm-mainnet
          - soneium-minato
          # - soneium-mainnet
          - monad-testnet
          - berachain-bepolia
          # - berachain-mainnet
          - blast-sepolia
          # - blast-mainnet
          # - metis-mainnet

    name: Deploy to ${{matrix.alchemy_chain_identifiers}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: |
          forge --version

      - name: Run DeployCore Script
        run: |
          forge script DeployCore --rpc-url https://${{ matrix.alchemy_chain_identifiers }}.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }} --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }} --broadcast --verify --retries 50
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          SALT: "0x81385ba264a7f8c1b8208abaa20f59081c2afc5415c2b57c383f951930ff6faa"
          EXPECTED_ADDRESS: "0xe0e0e02b1271d26dCBA2ac92f748dC24c8629Ff8"
